name: DisableItemFrameRotation
main: sososlik.disableitemframerotation.Plugin
version: 1.1.0
author: "Sososlik (sososlik@outlook.com)"
description: "Prevents players from rotating the item frames with right-click."
website: https://www.spigotmc.org/resources/disable-item-frame-rotation.33134/
commands:
permissions:
  disableitemframerotation.bypass:
     description: Allows you to bypass the protection.
     default: false
